# Generated by Django 4.1.4 on 2023-01-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_componentslist_related_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentslist',
            name='componentname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
