# Generated by Django 4.1.4 on 2023-01-26 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('news', '0010_componentslist_componentname'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='articleimage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='articletext',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='articleurl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
