# Generated by Django 4.1.4 on 2023-02-01 03:46

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_internalpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalpage',
            name='body',
            field=wagtail.fields.StreamField([('column', wagtail.blocks.StructBlock([('left', wagtail.blocks.CharBlock()), ('right', wagtail.blocks.RichTextBlock())], icon='user', template='column.html')), ('heading', wagtail.blocks.CharBlock(form_classname='title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], use_json_field=True),
        ),
    ]
