# Generated by Django 4.1.13 on 2024-12-04 09:43

from django.db import migrations, models
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_myappsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name_ru', models.CharField(max_length=255, verbose_name='Название тега на русском')),
                ('tag_name_en', models.CharField(max_length=255, verbose_name='Название тега на английском')),
            ],
            options={
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.AddField(
            model_name='newspage',
            name='news_tags',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='news.tags'),
        ),
    ]
