# Generated by Django 4.1.13 on 2026-01-11 11:48

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_tags_newspage_news_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='minisite_body',
            field=wagtail.fields.StreamField([('htmlslider', wagtail.blocks.StructBlock([('htmlslider', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('html', wagtail.blocks.RawHTMLBlock(required=True))])))]))], blank=True, use_json_field=True),
        ),
    ]
