# Generated by Django 4.1.13 on 2026-01-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0022_mainpage_minisite_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='mp_htmlslidershow',
            field=models.BooleanField(default=False, verbose_name='Показывать html слайдер'),
        ),
    ]
