# Generated by Django 4.1.13 on 2026-01-13 04:24

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('wagtailcore', '0083_workflowcontenttype'),
        ('news', '0023_mainpage_mp_htmlslidershow'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterProgramList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp_name', models.CharField(blank=True, max_length=50, null=True)),
                ('mp_text', wagtail.fields.RichTextField(blank=True)),
                ('mp_picture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('mp_related_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'verbose_name_plural': 'Master program list',
            },
        ),
        migrations.AddField(
            model_name='mainpage',
            name='mp',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='news.masterprogramlist'),
        ),
    ]
