# Generated by Django 4.1.4 on 2023-02-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeoplesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peoplecategory', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Группа',
            },
        ),
    ]
