# Generated by Django 4.1.4 on 2023-02-06 09:00

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
        ('wagtailimages', '0024_index_image_file_hash'),
        ('peoples', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peoplescategory',
            options={'verbose_name_plural': 'Группы людей'},
        ),
        migrations.CreateModel(
            name='PeoplesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('full_name', models.CharField(max_length=250)),
                ('short_discription', wagtail.fields.RichTextField(blank=True)),
                ('full_discription', wagtail.fields.RichTextField(blank=True)),
                ('people_categories', modelcluster.fields.ParentalManyToManyField(blank=True, to='peoples.peoplescategory')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
