# Generated by Django 4.1.4 on 2023-05-12 09:19

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_alter_projectpage_project_body"),
        ("peoples", "0004_peoplesresearcherpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="peoplespage",
            name="people_projects",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, to="projects.projectpage"
            ),
        ),
    ]
