# Generated by Django 4.1.4 on 2023-07-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peoples", "0005_peoplespage_people_projects"),
    ]

    operations = [
        migrations.AddField(
            model_name="peoplespage",
            name="order",
            field=models.IntegerField(blank=True, default=20),
        ),
    ]
