# Generated by Django 4.1.4 on 2023-02-28 12:11

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectsearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='project_body_bottom',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='subtitle')), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('leftheader', wagtail.blocks.StructBlock([('left', wagtail.blocks.CharBlock()), ('right', wagtail.blocks.RichTextBlock())])), ('imageleft', wagtail.blocks.StructBlock([('imgleft', wagtail.images.blocks.ImageChooserBlock()), ('txtright', wagtail.blocks.RichTextBlock())])), ('htmlcode', wagtail.blocks.RawHTMLBlock())], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='project_context',
            field=models.BooleanField(default=False, verbose_name='НЕ показывать результаты контекстного поиска'),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='project_slider',
            field=models.BooleanField(default=False, verbose_name='НЕ показывать слайдер сверху'),
        ),
    ]
