# Generated by Django 4.1.4 on 2023-05-12 09:19

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_projectpage_project_projects"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectpage",
            name="project_body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", wagtail.blocks.CharBlock(form_classname="subtitle")),
                    ("paragraph", wagtail.blocks.RichTextBlock()),
                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                    (
                        "leftheader",
                        wagtail.blocks.StructBlock(
                            [
                                ("left", wagtail.blocks.CharBlock()),
                                ("right", wagtail.blocks.RichTextBlock()),
                            ]
                        ),
                    ),
                    (
                        "imageleft",
                        wagtail.blocks.StructBlock(
                            [
                                ("imgleft", wagtail.images.blocks.ImageChooserBlock()),
                                ("txtright", wagtail.blocks.RichTextBlock()),
                            ]
                        ),
                    ),
                    (
                        "imagecenter",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "imgcenter",
                                    wagtail.images.blocks.ImageChooserBlock(),
                                ),
                                ("imgurl", wagtail.blocks.URLBlock(required=False)),
                                (
                                    "txtcenter",
                                    wagtail.blocks.RichTextBlock(required=False),
                                ),
                            ]
                        ),
                    ),
                    ("htmlcode", wagtail.blocks.RawHTMLBlock()),
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
    ]
