# Generated by Django 4.1.13 on 2024-06-20 13:13

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('minisite', '0002_remove_minisitelist_minisite_logo_list_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinisitePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('minisite_title_h1', models.CharField(blank=True, max_length=255, null=True)),
                ('minisite_news', models.BooleanField(default=False, verbose_name='Показывать новости')),
                ('minisite_body', wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='subtitle')), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('htmlcode', wagtail.blocks.RawHTMLBlock()), ('leftheader2', wagtail.blocks.StructBlock([('left', wagtail.blocks.CharBlock(required=False)), ('header_level', wagtail.blocks.IntegerBlock(default=3, help_text='Уровень заголовка', max_value=4, min_value=1)), ('color', wagtail.blocks.IntegerBlock(default=0, help_text='0 - no, 1 - blue, 2 - red')), ('position', wagtail.blocks.IntegerBlock(default=0, help_text='0 - no, 1 - external, 2 - internal')), ('right', wagtail.blocks.RichTextBlock(required=False)), ('rightcolor', wagtail.blocks.IntegerBlock(default=0, help_text='0 - no, 1 - blue, 2 - red')), ('rightborder', wagtail.blocks.RichTextBlock(required=False)), ('rightfinish', wagtail.blocks.RichTextBlock(required=False)), ('cta', wagtail.blocks.CharBlock(required=False)), ('url', wagtail.blocks.CharBlock(required=False))])), ('checklist2', wagtail.blocks.StructBlock([('bgimage', wagtail.images.blocks.ImageChooserBlock()), ('header', wagtail.blocks.CharBlock()), ('beforechecklisttext', wagtail.blocks.TextBlock(required=False)), ('afterchecklisttext', wagtail.blocks.TextBlock(required=False)), ('checklist', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('inchecklist', wagtail.blocks.StructBlock([('listheader', wagtail.blocks.RichTextBlock(required=False)), ('checklist', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('checktext', wagtail.blocks.RichTextBlock(required=False)), ('text', wagtail.blocks.RichTextBlock(required=False))])))]))])))]))], blank=True, use_json_field=True)),
                ('minisite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minisite_pages', to='minisite.minisitelist')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
