# Generated by Django 4.1.13 on 2024-06-21 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('minisite', '0003_minisitepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='minisitepage',
            name='minisite_bgimage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
