# Generated by Django 4.1.13 on 2024-09-12 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('minisite', '0004_minisitepage_minisite_bgimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='minisitelist',
            name='minisite_fon_color',
            field=models.CharField(blank=True, default='#fafafa', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='minisitelist',
            name='minisite_fon_textcolor',
            field=models.CharField(blank=True, default='#2165AD', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='minisitelist',
            name='minisite_fonblock',
            field=models.BooleanField(default=True, verbose_name='Показывать блок с фоновым рисунком и заголовком сайта'),
        ),
        migrations.AddField(
            model_name='minisitelist',
            name='minisite_leftlogo',
            field=models.BooleanField(default=False, verbose_name='Показывать блок с логотипом слева и заголовком сайта'),
        ),
        migrations.AddField(
            model_name='minisitelist',
            name='minisite_listlogo',
            field=models.BooleanField(default=True, verbose_name='Показывать список логотипов'),
        ),
        migrations.AddField(
            model_name='minisitelist',
            name='minisite_ll_fon_color',
            field=models.CharField(blank=True, default='#fafafa', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='minisitelist',
            name='minisite_ll_textcolor',
            field=models.CharField(blank=True, default='#2165AD', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='minisitelist',
            name='minisite_mainlogo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='minisitepage',
            name='minisite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='minisite_pages', to='minisite.minisitelist'),
        ),
    ]
