# Generated by Django 4.1.13 on 2024-09-13 05:11

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('minisite', '0005_minisitelist_minisite_fon_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='minisitepage',
            name='minisite_leftbody',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='subtitle')), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('htmlcode', wagtail.blocks.RawHTMLBlock()), ('leftheader2', wagtail.blocks.StructBlock([('left', wagtail.blocks.RichTextBlock(required=False)), ('header_level', wagtail.blocks.IntegerBlock(default=3, help_text='Уровень заголовка', max_value=4, min_value=1)), ('color', wagtail.blocks.IntegerBlock(default=0, help_text='0 - no, 1 - blue, 2 - red')), ('position', wagtail.blocks.IntegerBlock(default=0, help_text='0 - no, 1 - external, 2 - internal')), ('right', wagtail.blocks.RichTextBlock(required=False)), ('rightcolor', wagtail.blocks.IntegerBlock(default=0, help_text='0 - no, 1 - blue, 2 - red')), ('rightborder', wagtail.blocks.RichTextBlock(required=False)), ('rightfinish', wagtail.blocks.RichTextBlock(required=False)), ('cta', wagtail.blocks.CharBlock(required=False)), ('url', wagtail.blocks.CharBlock(required=False))])), ('checklist2', wagtail.blocks.StructBlock([('bgimage', wagtail.images.blocks.ImageChooserBlock()), ('header', wagtail.blocks.CharBlock()), ('beforechecklisttext', wagtail.blocks.TextBlock(required=False)), ('afterchecklisttext', wagtail.blocks.TextBlock(required=False)), ('checklist', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('inchecklist', wagtail.blocks.StructBlock([('listheader', wagtail.blocks.RichTextBlock(required=False)), ('checklist', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('checktext', wagtail.blocks.RichTextBlock(required=False)), ('text', wagtail.blocks.RichTextBlock(required=False))])))]))])))]))], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='minisitepage',
            name='minisite_onecolumn',
            field=models.BooleanField(default=False, verbose_name='Показывать блок во всю ширину экрана'),
        ),
        migrations.AddField(
            model_name='minisitepage',
            name='minisite_rightbody',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='subtitle')), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('htmlcode', wagtail.blocks.RawHTMLBlock()), ('leftheader2', wagtail.blocks.StructBlock([('left', wagtail.blocks.RichTextBlock(required=False)), ('header_level', wagtail.blocks.IntegerBlock(default=3, help_text='Уровень заголовка', max_value=4, min_value=1)), ('color', wagtail.blocks.IntegerBlock(default=0, help_text='0 - no, 1 - blue, 2 - red')), ('position', wagtail.blocks.IntegerBlock(default=0, help_text='0 - no, 1 - external, 2 - internal')), ('right', wagtail.blocks.RichTextBlock(required=False)), ('rightcolor', wagtail.blocks.IntegerBlock(default=0, help_text='0 - no, 1 - blue, 2 - red')), ('rightborder', wagtail.blocks.RichTextBlock(required=False)), ('rightfinish', wagtail.blocks.RichTextBlock(required=False)), ('cta', wagtail.blocks.CharBlock(required=False)), ('url', wagtail.blocks.CharBlock(required=False))])), ('checklist2', wagtail.blocks.StructBlock([('bgimage', wagtail.images.blocks.ImageChooserBlock()), ('header', wagtail.blocks.CharBlock()), ('beforechecklisttext', wagtail.blocks.TextBlock(required=False)), ('afterchecklisttext', wagtail.blocks.TextBlock(required=False)), ('checklist', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('inchecklist', wagtail.blocks.StructBlock([('listheader', wagtail.blocks.RichTextBlock(required=False)), ('checklist', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('checktext', wagtail.blocks.RichTextBlock(required=False)), ('text', wagtail.blocks.RichTextBlock(required=False))])))]))])))]))], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='minisitepage',
            name='minisite_twocolumn',
            field=models.BooleanField(default=False, verbose_name='Показывать блок в две колонки'),
        ),
        migrations.AlterField(
            model_name='minisitepage',
            name='minisite_body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='subtitle')), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('htmlcode', wagtail.blocks.RawHTMLBlock()), ('leftheader2', wagtail.blocks.StructBlock([('left', wagtail.blocks.RichTextBlock(required=False)), ('header_level', wagtail.blocks.IntegerBlock(default=3, help_text='Уровень заголовка', max_value=4, min_value=1)), ('color', wagtail.blocks.IntegerBlock(default=0, help_text='0 - no, 1 - blue, 2 - red')), ('position', wagtail.blocks.IntegerBlock(default=0, help_text='0 - no, 1 - external, 2 - internal')), ('right', wagtail.blocks.RichTextBlock(required=False)), ('rightcolor', wagtail.blocks.IntegerBlock(default=0, help_text='0 - no, 1 - blue, 2 - red')), ('rightborder', wagtail.blocks.RichTextBlock(required=False)), ('rightfinish', wagtail.blocks.RichTextBlock(required=False)), ('cta', wagtail.blocks.CharBlock(required=False)), ('url', wagtail.blocks.CharBlock(required=False))])), ('checklist2', wagtail.blocks.StructBlock([('bgimage', wagtail.images.blocks.ImageChooserBlock()), ('header', wagtail.blocks.CharBlock()), ('beforechecklisttext', wagtail.blocks.TextBlock(required=False)), ('afterchecklisttext', wagtail.blocks.TextBlock(required=False)), ('checklist', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('inchecklist', wagtail.blocks.StructBlock([('listheader', wagtail.blocks.RichTextBlock(required=False)), ('checklist', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('checktext', wagtail.blocks.RichTextBlock(required=False)), ('text', wagtail.blocks.RichTextBlock(required=False))])))]))])))]))], blank=True, use_json_field=True),
        ),
    ]
