# Generated by Django 4.1.4 on 2023-02-14 13:41

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0004_peoplesresearcherpage'),
        ('menuitem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menupage',
            name='menupage_avtor',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='peoples.peoplescategory'),
        ),
    ]
