# Generated by Django 4.1.4 on 2023-02-15 11:45

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('menuitem', '0002_menupage_menupage_avtor'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workcategory', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Направления деятельности',
            },
        ),
        migrations.CreateModel(
            name='WorkCategoryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('menuitempage', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='workcategory_list', to='menuitem.menupage')),
                ('workcategoryitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='menuitem.workcategory')),
            ],
            options={
                'verbose_name': 'Список направлений',
                'verbose_name_plural': 'Список направлений',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='menupage',
            name='menupage_workcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='menuitem.workcategory'),
        ),
    ]
