# Generated by Django 4.1.4 on 2023-02-15 14:17

from django.db import migrations, models
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0004_peoplesresearcherpage'),
        ('menuitem', '0003_workcategory_workcategorylist_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menupage',
            options={'verbose_name': 'Страница для пукнта меню', 'verbose_name_plural': 'Страницы в пункте меню'},
        ),
        migrations.AlterModelOptions(
            name='workcategory',
            options={'verbose_name': 'Категория контента', 'verbose_name_plural': 'Категории контента'},
        ),
        migrations.AlterModelOptions(
            name='workcategorylist',
            options={'ordering': ['sort_order'], 'verbose_name': 'Список категорий контента', 'verbose_name_plural': 'Список категорий контента'},
        ),
        migrations.AlterField(
            model_name='menupage',
            name='menupage_avtor',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='peoples.peoplespage'),
        ),
        migrations.AlterField(
            model_name='menupage',
            name='menupage_date',
            field=models.DateField(verbose_name='Дата публикации или дата реализации проекта'),
        ),
    ]
