# Generated by Django 4.1.4 on 2023-02-16 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuitem', '0004_alter_menupage_options_alter_workcategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menupage',
            name='menupage_workcategory',
        ),
    ]
