# Generated by Django 4.1.4 on 2023-02-16 11:22

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('menuitem', '0007_alter_menupage_menupage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menupage',
            name='menupage_body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='subtitle')), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('leftheader', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('left', wagtail.blocks.CharBlock()), ('right', wagtail.blocks.RichTextBlock())]))), ('htmlcode', wagtail.blocks.RawHTMLBlock())], blank=True, use_json_field=True),
        ),
    ]
