# Generated by Django 4.1.4 on 2023-02-18 12:17

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projectpage_options_projectpage_project_avtor_and_more'),
        ('menuitem', '0010_alter_menupage_menupage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='menupage',
            name='menupage_projects',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='projects.projectpage'),
        ),
    ]
