# Generated by Django 4.1.4 on 2023-02-21 10:42

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('menuitem', '0011_menupage_menupage_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='menupage',
            name='menupage_body_bottom',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='subtitle')), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('leftheader', wagtail.blocks.StructBlock([('left', wagtail.blocks.CharBlock()), ('right', wagtail.blocks.RichTextBlock())])), ('imageleft', wagtail.blocks.StructBlock([('imgleft', wagtail.images.blocks.ImageChooserBlock()), ('txtright', wagtail.blocks.RichTextBlock())])), ('htmlcode', wagtail.blocks.RawHTMLBlock())], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='menupage',
            name='menupage_slider',
            field=models.BooleanField(default=False, verbose_name='НЕ показывать слайдер сверху'),
        ),
    ]
