# Generated by Django 4.1.4 on 2023-02-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuitem', '0012_menupage_menupage_body_bottom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menupage',
            name='menupage_context',
            field=models.BooleanField(default=False, verbose_name='НЕ показывать результаты контекстного поиска'),
        ),
    ]
